<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Esri.ArcGISRuntime.WPF" Version="200.8.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CommandMessaging\CommandMessaging.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Resources\campus-routes.geodatabase"
          Link="campus-routes.geodatabase"
          CopyToOutputDirectory="PreserveNewest"
          Condition="Exists('Resources\campus-routes.geodatabase')" />
  </ItemGroup>
</Project>
