<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <Authors>Team Milano</Authors>
    <Company>Esri</Company>
    <Description>Simple application to test Stream Layer functionality.</Description>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <Prefer32Bit>false</Prefer32Bit>
    <Configurations>Debug;Release</Configurations>
    <ApplicationIcon>demo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Esri.Calcite.WPF" Version="1.0.0-rc.1" />
    <PackageReference Include="Esri.ArcGISRuntime" Version="200.8.1" />
    <PackageReference Include="Esri.ArcGISRuntime.WPF" Version="200.8.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Content\sandy_uvr.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Content\sandy_uvr_prev.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
